### ISSUE TITLE
m1 芯片可以使用吗

### ISSUE THREAD

**Issue by shuifa** [dotnetcore/FastGithub#104]
如题

**Comment by EzrealJ** [comment]
Duplicate of #97

**Comment by EzrealJ** [comment]
不直接提供该平台的编译文件，但你可以自行使用.NET 6的SDK   使用 -r osx.11.0-arm64 编译
不承诺可用性，因为我们没有设备，无法测试该平台

**Comment by imeteora** [comment]
MBP M1 max 亲测可用

**Comment by oushuifa** [comment]
> MBP M1 max 亲测可用。 目前是arch是x86_64的，理论上系统自动用rosetta 2环境下运行这个程序，目前我的情况是可以用的。不过，命令行下似乎还是会有一些问题。持续观察中。。。

怎么操作的啊。。不知道怎么编译

**Comment by blllld** [comment]
> 

貌似已经支持了，但是效果不是很好
