### ISSUE TITLE
windows下的hosts如果里面原来有中文,经过这个修改后会乱码.

### ISSUE THREAD

**Issue by lifetin** [dotnetcore/FastGithub#105]
**Bug描述**
Bug的详细描述内容

windows下的hosts如果里面原来有中文,经过这个修改后会乱码.

**重现步骤**
1.  xxx
2.  yyy
3.  zzz
 

**软件信息**
 - 操作系统: [e.g. win10-x64]
 - FastGithub： [e.g.  v2.0.0]

**Comment by EzrealJ** [comment]
https://github.com/dotnetcore/FastGithub/blob/001c6dddf7371af6f165f631b33ba2a028496a5f/FastGithub.PacketIntercept/Dns/HostsConflictSolver.cs#L49

https://github.com/dotnetcore/FastGithub/blob/001c6dddf7371af6f165f631b33ba2a028496a5f/FastGithub.PacketIntercept/Dns/HostsConflictSolver.cs#L68

🤔考虑使用系统代码页的Encoding
@xljiulang

**Comment by SadPencil** [comment]
hosts文件也不一定是系统代码页的encoding，如果有人用UTF-8写的hosts，系统代码页GB18030，这样一改也会乱码

**Comment by EzrealJ** [comment]
参阅代码实现，现在使用的是读取文件的Encoding，并非系统代码页的Encoding
