### ISSUE TITLE
连接异常

### ISSUE THREAD

**Issue by azazazazaz520** [dotnetcore/FastGithub#108]
**访问GitHub时显示以下字符：**
{"error":"Request","message":"找不到任何可成功连接的IP (Authentication failed, see inner exception.) (Authentication failed, see inner exception.) (github.com:443)"}
**软件信息**
 - 操作系统: Windows 7（内部版本7601）
 - FastGithub：v2.1.2

**Comment by EzrealJ** [comment]
根据你提供的错误文本，这个错误可能是由你的操作系统导致的；windows7可能在TLS的支持方面有一些缺陷；这可能导致无法和网站正常建立连接。fastgithub早已停止对Windows7的支持，微软也停止了对Windows7的支持，您可以更换仍受支持的其它操作系统，然后重试
