### ISSUE TITLE
与本地主机环境冲突，绑定的域名访问不了

### ISSUE THREAD

**Issue by xiedandan** [dotnetcore/FastGithub#110]
**Bug描述**
win10使用小皮面板(phpstudy)创建主机，绑定域名chun.test，访问会返回{
    "error": "Request",
    "message": "找不到任何可成功连接的IP (chun.test:80)"
}
退出 FastGithub.UI后就能访问了
 
**软件信息**
1.  win10 X64
2.  FastGithub.UI v2.1.2

**Comment by xljiulang** [comment]
你要把域名chun.test解析为非回环IP
