### ISSUE TITLE
无法访问本地80端口的内容

### ISSUE THREAD

**Issue by L33Z22L11** [dotnetcore/FastGithub#111]
**Bug描述**
使用期间无法访问127.0.0.1:80

**重现步骤**
1.  在vscode中使用liveserver部署静态网页到80端口
2.  打开127.0.0.1显示404
3.  更换端口则liveserver正常运作
 

**软件信息**
 - 操作系统: Windows 8.1 x64
 - FastGithub： v2.1.2

**Comment by xljiulang** [comment]
设计如此

**Comment by L33Z22L11** [comment]
你说得对，我看到配置文件了
