### ISSUE TITLE
Mac 增加 Homebrew 安装方式

### ISSUE THREAD

**Issue by PPP1G** [dotnetcore/FastGithub#112]
如题，希望能 `brew install fastgithub`之类的一键安装，以及配置流程能够简化&自动唤起系统代理设置

**Comment by EzrealJ** [comment]
你好,目前在所有平台暂时没有通过任何包管理工具分发的计划，感谢你的提议，如果我们计划通过除github之外的渠道分发，会考虑你的提议。
