### ISSUE TITLE
系统找不到指定的文件

### ISSUE THREAD

**Issue by YQisme** [dotnetcore/FastGithub#116]
![image](https://user-images.githubusercontent.com/80308783/151690636-bbf972a4-2e4d-464a-a601-b6e083209797.png)

**Comment by EzrealJ** [comment]
需要提供更详细的资料帮助定位问题.
1、OS和OS的版本
2、FastGithub的版本
3、你运行的目录和FastGithub的文件目录
期待你的回复。

**Comment by YQisme** [comment]
1.Windows 10 专业版 21H1（操作系统版本19043.1466）

**Comment by YQisme** [comment]
问题已解决，先`fastgithub.exe stop`再`fastgithub.exe start`后就好了
