### ISSUE TITLE
以服务方式启动会导致outlook邮箱无法添加新账户登录,无法接收邮件

### ISSUE THREAD

**Issue by yzqdev** [dotnetcore/FastGithub#118]
**Bug描述**
Bug的详细描述内容

`fastgithub.exe start`以服务方式启动会导致outlook邮箱无法登录且无法接收邮件

**重现步骤**
1.  用`fastgithub.exe start`方式启动代理
2.  打开windows10自带的邮箱进行添加邮箱登录的操作
3. 邮箱会出现`0x80190001`错误,无法登录且无法接收邮件
其他需要登录的软件,比如onenote等也是`0x80190001`错误
如下图所示
 
![image](https://user-images.githubusercontent.com/20037151/153270013-ed10283d-419f-48cf-a764-5418a41bda62.png)

![image](https://user-images.githubusercontent.com/20037151/153269977-b1a0c104-70b1-4c1b-b200-200b087e92e8.png)

**软件信息**
 - 操作系统:  win10-x64 版本: 21h2(19044)
 - FastGithub： v2.1.3

**Comment by EzrealJ** [comment]
你好，如果你在使用Microsoft服务时受到了影响，可以尝试删除配置文件夹中的appsettings.microsoft.json，这样FastGithub不会尝试对Microsoft的服务进行加速，这或许对你的情况有所帮助
[appsettings.microsoft.json](https://github.com/dotnetcore/FastGithub/blob/1685a5cf3262159c6f92c822c7552ffe0cd85462/FastGithub/appsettings/appsettings.microsoft.json)


这些配置的依据是[这里](https://docs.microsoft.com/en-us/azure/devops/organizations/security/allow-list-ip-url?view=azure-devops&tabs=IP-V4);添加它的本意是为了加速Microsoft的服务

**Comment by yzqdev** [comment]
> 你好，如果你在使用Microsoft服务时受到了影响，可以尝试删除配置文件夹中的appsettings.microsoft.json，这样FastGithub不会尝试对Microsoft的服务进行加速，这或许对你的情况有所帮助 [appsettings.microsoft.json](https://github.com/dotnetcore/FastGithub/blob/1685a5cf3262159c6f92c822c7552ffe0cd85462/FastGithub/appsettings/appsettings.microsoft.json)
> 
> 这些配置的依据是[这里](https://docs.microsoft.com/en-us/azure/devops/organizations/security/allow-list-ip-url?view=azure-devops&tabs=IP-V4);添加它的本意是为了加速Microsoft的服务

感谢,您的方法确实有用
