### ISSUE TITLE
软件导致api.nuget.org 解析为127.0.0.1

### ISSUE THREAD

**Issue by yangbocheng** [dotnetcore/FastGithub#119]
**Bug描述**
如上，开启程序后，会导致ping api.nuget.org 始终指向127.0.0.1 ， 这导致了在wsl2-ubuntu中，dotnet restore因获取nuget信息失败而始终无法下载nuget包。
![image](https://user-images.githubusercontent.com/32633109/153315230-90e5b3a5-2462-4a2a-99e8-b99804e1d9f4.png)
 该如何解决问题呢？
**软件信息**
 - 安装了docker-desktop 并开启了该软件
 - 操作系统: [win10-x64]
 - FastGithub： [v2.1.3]

**Comment by EzrealJ** [comment]
你好，找到配置文件 appsettings/appsettings.packages.json 删除nuget节点，重新启动FastGithub即可。

[参考](https://github.com/dotnetcore/FastGithub/blob/1685a5cf3262159c6f92c822c7552ffe0cd85462/FastGithub/appsettings/appsettings.packages.json#L4)

**Comment by yangbocheng** [comment]
谢谢指导 。已按提示解决
