### ISSUE TITLE
如果Windows上以服务方式开启，直接重启电脑，会不会上不了网

### ISSUE THREAD

**Issue by mendax1234** [dotnetcore/FastGithub#121]
**Bug描述**
Bug的详细描述内容

**重现步骤**
1.  xxx
2.  yyy
3.  zzz
 
问题如标题所示，

**软件信息**
 - 操作系统: [e.g. win10-x64]
 - FastGithub： [e.g.  v2.0.0]

**Comment by mendax1234** [comment]
以服务方式启动的话会开机自启动吗？

**Comment by xljiulang** [comment]
会。
