### ISSUE TITLE
最新版使用命令行以服务启动占用内存过高

### ISSUE THREAD

**Issue by xiaochen0517** [dotnetcore/FastGithub#122]
不知道这是正常情况还是出问题了，占用了100+的内存。

![image](https://user-images.githubusercontent.com/30149408/153970664-949ca7ae-c7eb-4e46-b8b0-e4533508e501.png)

总觉得有点不太正常，版本v2.1.3

**Comment by xljiulang** [comment]
Server GC模式，是这个占用。
