### ISSUE TITLE
Win7不能使用啊

### ISSUE THREAD

**Issue by skyformat99** [dotnetcore/FastGithub#123]
**Bug描述**
启动的时候，提示计算机缺少:   api-ms-win-core-winrt-l1-1-0.dll

**重现步骤**
下载，启动即可

**软件信息**
 - 操作系统: [e.g. win7-x64]
 - FastGithub： [e.g.  v2.0.0]

**Comment by xljiulang** [comment]
不支持win7

**Comment by flyang2010** [comment]
> **Bug描述** 启动的时候，提示计算机缺少: api-ms-win-core-winrt-l1-1-0.dll
> 
> **重现步骤** 下载，启动即可
> 
> **软件信息**
> 
> * 操作系统: [e.g. win7-x64]
> * FastGithub： [e.g.  v2.0.0]

没用，下载了这个dll，但是还是不行
