### ISSUE TITLE
linux系统无法访问raw.githubusercontent.com域名下的静态文件

### ISSUE THREAD

**Issue by yzqdev** [dotnetcore/FastGithub#126]
**Bug描述**

## 偶发性问题
 使用fastgithub时，linux有时出现无法访问github仓库的静态文件,图片,字体,等等(来自raw.githubusercontent.com域名的静态文件)的情况,，同一个网络下的Windows从未出现此问题

## 访问github的静态图片,结果无法显示
![2022-02-28 20-11-39屏幕截图](https://user-images.githubusercontent.com/20037151/155984243-e5536037-23c5-46ba-845e-986eb519339f.png)
![2022-02-28 20-11-56屏幕截图](https://user-images.githubusercontent.com/20037151/155984250-cdb7a3e3-4cd1-4ca5-8545-11e67ee634fc.png)
![2022-02-28 20-27-11屏幕截图](https://user-images.githubusercontent.com/20037151/155984252-f2b5af48-cb1d-49f6-9832-0abf64d6c10f.png)

**重现步骤**
1.  运行fastgithub(`sudo ./fastgithub`直接运行或者`sudo ./fastgithub start`以服务方式运行)
2.  访问本仓库静态图片
3.  图片无法正常显示
 

**软件信息**
 - 操作系统:  linuxmint 20.3(基于ubuntu Focal ,linux kernel 5.4.0)
 - FastGithub： v2.1.4

**Comment by xljiulang** [comment]
看上去，curl没有获得https_proxy环境变量的代理值。

**Comment by crazy-canux** [comment]
卧槽，你咋知道我用的curl

**Comment by crazy-canux** [comment]
终端配一下proxy就可以了。

**Comment by yzqdev** [comment]
> 终端配一下proxy就可以了。

我在`/etc/profile`里面配的代理:
```bash
export http_proxy=http://127.0.0.1:38457

export https_proxy=http://127.0.0.1:38457
```
不过这个问题有时候出现,有时候不出现,也有可能是github的问题
