### ISSUE TITLE
360显示有trojan病毒

### ISSUE THREAD

**Issue by mendax1234** [dotnetcore/FastGithub#130]
**Bug描述**
Bug的详细描述内容
360显示有病毒，怎么回事
**重现步骤**
1.  xxx
2.  yyy
3.  zzz
 

**软件信息**
 - 操作系统: [e.g. win10-x64]
 - FastGithub： [e.g.  v2.0.0]
 - FastGithub v2.1.4

**Comment by EzrealJ** [comment]
启动时会对系统dns查询注入拦截以实现加速，会被部分杀软识别为病毒行为。
解决方案:

1. 添加为该杀毒软件的信任程序
2. 卸载该杀毒软件
3. 换一个杀毒软件
4. 彻底删除FastGithub

**Comment by mendax1234** [comment]
好的，谢谢
