### ISSUE TITLE
开机自启

### ISSUE THREAD

**Issue by Tender-hjd** [dotnetcore/FastGithub#134]
Windows版本在哪里设置开机自启?

**Comment by VAllens** [comment]
好好的`Readme`不看

windows-x64服务 
* `fastgithub.exe start` // 以windows服务安装并启动
* `fastgithub.exe stop` // 以windows服务卸载并删除

**Comment by Tender-hjd** [comment]
抱歉，README说的不太清楚，我以为启动之后一关机，下次还得再执行一次这个命令




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dotnetcore/FastGithub"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月20日(星期天) 下午2:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dotnetcore/FastGithub] 开机自启 (Issue #134)





 
好好的Readme不看
 
windows-x64服务
  
fastgithub.exe start // 以windows服务安装并启动
 
fastgithub.exe stop // 以windows服务卸载并删除
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by VAllens** [comment]
Close issues 吧 :)
