### ISSUE TITLE
Windows电脑占用CPU资源高

### ISSUE THREAD

**Issue by CarlosAdmin** [dotnetcore/FastGithub#137]
**Bug描述**
占用CPU资源高
![image](https://user-images.githubusercontent.com/3022231/159837573-612aeb8a-302c-46ce-b0ac-56b46d863b19.png)

**重现步骤**
1.  打开客户端CPU高
2.  关闭客户端CPU降下来
3. 未访问GitHub相关网站
 

**软件信息**
 - 操作系统: [win10-x64]
 - FastGithub： [v2.1.4]
[log20220324.txt](https://github.com/dotnetcore/FastGithub/files/8338267/log20220324.txt)

**Comment by sgf** [comment]
隐藏窗口就降下来了.很正常,因为作者加了个并没什么卵用的动态图
