### ISSUE TITLE
会导致托管在github的静态站点无法访问

### ISSUE THREAD

**Issue by crazy-canux** [dotnetcore/FastGithub#139]
**Bug描述**
https://crazy-canux.github.io/  是我托管在github的站点，通过域名  canuxcheng.com 解析。无法访问。

**重现步骤**
1.  xxx
2.  yyy
3.  zzz
 

**软件信息**
 - 操作系统: macos12.2.1
 - FastGithub： v2.1.4

**Comment by Cccc-owo** [comment]
我在自己电脑上试了一下，没问题啊
![image](https://user-images.githubusercontent.com/47687154/160231058-22ef4a82-dc3b-4f9c-bac5-2ac1395631a3.png)
