### ISSUE TITLE
尝试在WSL中使用fastgithub时无效果

### ISSUE THREAD

**Issue by Ban-Tui-Ban-Jiu** [dotnetcore/FastGithub#158]
**WSL中使用fastgithub无法连接Github**
Windows中使用fastgithub时能够正常连接GitHub，但在WSL子系统中连接失败，尝试过程中按照Linux x64方法设置。

**WSL系统**
Ubutnu 20.04 LTS

**Comment by registerGen** [comment]
WSL 用的不是 systemd，所以 `fastgithub start/stop` 不行。

但是直接 `fastgithub` 是可以的。

**Comment by Ban-Tui-Ban-Jiu** [comment]
已收到您的来信，谢谢

**Comment by Ban-Tui-Ban-Jiu** [comment]
感谢您的帮助！
