### ISSUE TITLE
无法启动此程序，因为计算机丢失```api-ms-win-core-winrt-l1-1-0.dll```

### ISSUE THREAD

**Issue by 2926295173** [dotnetcore/FastGithub#16]

**Comment by 2926295173** [comment]
建议作者将这个库添加进releases

**Comment by xljiulang** [comment]
你的系统具体版本是多少

**Comment by 2926295173** [comment]
win7 64 sp1

**Comment by xljiulang** [comment]
你要更新你的操作系统：
https://support.microsoft.com/en-us/topic/update-for-universal-c-runtime-in-windows-c0514201-7fe6-95a3-b0a5-287930f3560c

**Comment by fawdlstty** [comment]
遇到相同问题，win7，已安装vs2017、vs2019以及vc可再发行包，根据链接下载了补丁，提示已经安装过了，但依旧存在这个问题

**Comment by xljiulang** [comment]
这个可以确定是vc运行时的原因，目前使用.net6发布，在win7上会出现这个现象

**Comment by xljiulang** [comment]
see https://github.com/dotnet/sdk/issues/16499

**Comment by xljiulang** [comment]
问题已解决，1.1.2版本将增加win7x64的发布包。

**Comment by bbingz** [comment]
后续的包都没有win7x64的发布包了吗？ 教学需要，学校老机房都是Win7。

**Comment by EzrealJ** [comment]
你好，最后支持win7的版本是2.0.4；或者使用v1版本部署为局域网的dns服务器
