### ISSUE TITLE
MacOS Mojave 10.14.6 OneDrive 无法使用

### ISSUE THREAD

**Issue by fumiama** [dotnetcore/FastGithub#170]
**Bug描述**
网页是可以访问的，但是APP无法使用，一旦关闭fastgithub则立即恢复正常。

**重现步骤**
1.  打开fastgithub
2.  拖入一个文件，文件一直无法上传
3.  关闭fastgithub，文件立即上传成功
 

**软件信息**
 - 操作系统: MacOS Mojave 10.14.6
 - FastGithub： v2.1.4
 - 使用了自动代理配置

**Comment by EzrealJ** [comment]
删除appsettings文件夹下OneDrive相关的配置文件

**Comment by fumiama** [comment]
可以了，不过能够被正常代理上就更好了，因为有可能od访问缓慢。
