### ISSUE TITLE
开启fastgithub服务后每次打开VS时提示无法登录

### ISSUE THREAD

**Issue by cngege** [dotnetcore/FastGithub#171]
**Bug描述**
Bug的详细描述内容
开启fastgithub服务后每次打开VS时提示无法登录

**重现步骤**
开启fastGitHub服务后 打开任意VS项目均会弹窗提示 登录失败
 

**软件信息**
 - 操作系统: [e.g. win10-x64]
 - FastGithub： [e.g.  v2.1.4]

<img src="https://i.postimg.cc/CMRQLjSy/image.png" />

**Comment by yzqdev** [comment]
可以尝试删除配置文件夹中的`appsettings.microsoft.json`，这样FastGithub不会尝试对Microsoft的服务进行加速,我之前是这么解决的

**Comment by cngege** [comment]
> 可以尝试删除配置文件夹中的`appsettings.microsoft.json`，这样FastGithub不会尝试对Microsoft的服务进行加速,我之前是这么解决的

感谢  成功了
