### ISSUE TITLE
Linux版本无法使用

### ISSUE THREAD

**Issue by KENAN1412** [dotnetcore/FastGithub#172]
linux按照配置文档配置但无法使用

**Comment by EzrealJ** [comment]
请附错误详情

**Comment by KENAN1412** [comment]
<img width="711" alt="捕获" src="https://user-images.githubusercontent.com/77651819/172078836-d5f94a60-9eb0-4806-aa60-0f438b62f33b.PNG">

**Comment by KENAN1412** [comment]
![image](https://user-images.githubusercontent.com/77651819/172078910-f85b62ec-dd29-43d2-b3dc-59ae43409d63.png)

**Comment by KENAN1412** [comment]
![image](https://user-images.githubusercontent.com/77651819/172078961-a87d00fb-d88b-44dc-89f3-db45d9c86763.png)

Ubuntu 20.0.4

**Comment by KENAN1412** [comment]
在 /etc/profile文件下也
export http_proxy=http://127.0.0.1:38457

export https_proxy=http://127.0.0.1:38457

**Comment by EzrealJ** [comment]
linux 没有干预系统的dns，所以也不会重定向github的解析地址，ping的时候和几乎不会有区别；只有在你使用http访问的时候才会生效。并且不保证加速效果

**Comment by KENAN1412** [comment]
https不能重定向是不是？
我现在通过http能够上GitHub了。
我想能不能给fast GitHub权限使它能够修改系统的dns

**Comment by EzrealJ** [comment]
不能 那是1.x做的事

**Comment by KENAN1412** [comment]
OK,感谢

**Comment by woldsn0201** [comment]
@EzrealJ 

> linux 没有干预系统的dns，所以也不会重定向github的解析地址，ping的时候和几乎不会有区别；只有在你使用http访问的时候才会生效。并且不保证加速效果

我也遇到了同样的问题
环境一样：
win10主机，Ubuntu20_64虚拟机，网络连接模式为桥接直连物理网络。
直接使用fastgithub_linux-x64版本，使用多种方式配置Ubuntu网络代理。
还是出现：
moyuqing@ubuntu20:~/tool/fastgithub_linux-x64$ sudo ./fastgithub 
[sudo] moyuqing 的密码： 
2023-03-29T09:07:27.7386972+08:00 [INF]
FastGithub.HttpServer
已监听http://localhost:38457，http代理服务启动完成

2023-03-29T09:07:28.4213415+08:00 [INF]
FastGithub.AppHostedService
FastGithub启动完成，当前版本为v2.1.4，访问 https://github.com/dotnetcore/fastgithub 关注新版本

2023-03-29T09:07:28.5339628+08:00 [WRN]
FastGithub.DomainResolve.DnscryptProxy
dnscrypt-proxy启动失败：An error occurred trying to start process '/home/moyuqing/tool/fastgithub_linux-x64/dnscrypt-proxy/dnscrypt-proxy' with working directory 'dnscrypt-proxy'. Permission denied

2023-03-29T09:07:29.4443154+08:00 [WRN]
FastGithub.AppHostedService
请设置系统自动代理为http://127.0.0.1:38457，或手动代理http/https为127.0.0.1:38457

我不打算在Ubuntu浏览github 只需要使用git就行。
我配置了git代理
^Cmoyuqing@ubuntu20:~/tool/fastgithub_linux-x64$ cat ~/.gitconfig 
[push]
        default = simple
[commit]
        template = /home/moyuqing/.commit_template
[core]
        editor = vim
        fileMode = false

[http]
	proxy = http://127.0.0.1:38457
	sslverify = false
[https]
	proxy = http://127.0.0.1:38457

在公司能clone很快，在家有时候就不行。是不是Ubuntu无法保证clone速率啊

**Comment by EzrealJ** [comment]
任何情况下都不保证速率，它毕竟不是梯子
