### ISSUE TITLE
为啥我在fast GitHub文件的控制台输入"fastgithub.exe on"也有反应

### ISSUE THREAD

**Issue by qiuyiyang0521** [dotnetcore/FastGithub#181]
![屏幕截图 2022-07-03 082803](https://user-images.githubusercontent.com/104243947/177019966-28d4a380-64f1-4137-b3d4-25f765e173bc.png)

**Comment by qiuyiyang0521** [comment]
在线求解

**Comment by yzqdev** [comment]
See here https://github.com/dotnetcore/FastGithub/blob/bcc0556fd0eb975b705865fa2b5b9a16941ae657/FastGithub/ServiceExtensions.cs#L56-L133

**Comment by qiuyiyang0521** [comment]
emmmmm......

**Comment by qiuyiyang0521** [comment]
用"start"，还是"on"。

**Comment by EzrealJ** [comment]
临时启动不加参数。作为服务注册使用start，停止服务用stop  只能启动单个实例

**Comment by qiuyiyang0521** [comment]
谢谢
