### ISSUE TITLE
win 11 下会代理“login.microsoftonline.com”导致 teams 无法登录。

### ISSUE THREAD

**Issue by Mutuduxf** [dotnetcore/FastGithub#192]
**Bug描述**
以服务的方式启动后会代理“login.microsoftonline.com”，ping 这个域名的时候返回的 IP 是 127.0.0.1，这导致 teams 等软件无法登陆。

**重现步骤**
1.  cmd 进入 fastgithub 文件夹路径执行命令“fastgithub.exe start”
2.  cmd 执行 “ping login.microsoftonline.com”
 

**软件信息**
 - 操作系统: [e.g. win11-x64]
 - FastGithub： [e.g.  v2.1.4.0]

**Comment by xljiulang** [comment]
你可以删除配置文件：appsettings.microsoft.json

**Comment by Mutuduxf** [comment]
> 

谢谢，看了下配置文件里的东西挺多的，请问直接删掉会不会有影响？或者我只删掉里面“*.microsoftonline.com”这一项？

**Comment by xljiulang** [comment]
删除整个文件

**Comment by Mutuduxf** [comment]
> 删除整个文件

好的，谢谢。
