### ISSUE TITLE
如何设置白名单

### ISSUE THREAD

**Issue by qx4235** [dotnetcore/FastGithub#20]
内网中有些站点使用代理后无法打开 ，怎么设置白名单，代理时绕过这些站点，3q!!
remark:东西很好用，感觉比devsidercar更好用

**Comment by xljiulang** [comment]
内网如果你用ip访问，就不会经过fastgithub，如果使用域名，且这个域名不幸刚好能被fastgithub的dns解析，你可以选择如下的某一种操作：
* 在系统的hosts文件加入你的域名和ip
* 在fastgithub 的配置文件，加入你的域名，域名配置IPAddress值

**Comment by qx4235** [comment]
tks
