### ISSUE TITLE
找不到文件cacert/fastgithub.cer

### ISSUE THREAD

**Issue by mock123456** [dotnetcore/FastGithub#207]
我已经完成了全部步骤，火狐浏览器提示，未连接：有潜在的安全问题。
按照文档所示添加cacert/fastgithub.cer进证书机构内，但是发现没有找到fastgithub.cer这个文件，只有fastgithub.crt和fastgithub.key。因此无法导入成功

**Comment by vinfon** [comment]
一样，我用的是macm1也没有
