### ISSUE TITLE
确实可用，特来感谢一下

### ISSUE THREAD

**Issue by lucktu** [dotnetcore/FastGithub#218]
我身边有一个windows7，还是一个32版的，这个确实不能用。

但我的身边还有一个小主机，装的是ubuntu18.04，使用远程桌面的方式登录上面的FF浏览器，简单运行设置一下代理，就真的跑起来了，而且速度还真的不错，真的是很快，比翻墙还快！而且之前转圈的下载页面也一切正常，真是神奇！！（使用的是2.1.4版本）

有点奢望的是，能将此代理共享给其他机器或手机使用就更好了。

不管怎么说，今后登录 github.com 就真的靠您了。可怜的中国人啊，上个正规的合法的 github.com，还需采用这么高科技的方法！！

**Comment by xizhesun** [comment]
天真，github上攻击中共的邪教和政治帖还少嘛。你只看到限制你获取信息了，其实封GitHub限制有害信息传播是对的，限制技术分析是错的，这个很难平衡。科研院所可以直接找电信服务商申请网络专线，个人开发者也可以购买备案的商用VPN解决这个问题。

**Comment by xljiulang** [comment]
非问题问题，关闭。
