### ISSUE TITLE
能否搭配adguard-home为局域网提供服务？

### ISSUE THREAD

**Issue by azureqaq** [dotnetcore/FastGithub#223]
**Bug描述**
- 我想使用此软件搭配 [adguard-home](https://github.com/AdguardTeam/AdGuardHome) 来实现局域网分享功能
- 请问能否实现？
- 如果可以我该如何做？

**软件信息**
 - 操作系统: [linux-x86_64]
 - FastGithub： [v2.1.4]

**Comment by EzrealJ** [comment]
你好  
1.x版本是完全基于DNS选优设计的，可以搭配adguard；
2.x版本则使用了一些非DNS角度的技术(有些甚至是Windows特有的)，所以仅为本机服务

**Comment by azureqaq** [comment]
非常感谢
