### ISSUE TITLE
开启后FastGithub不能关闭是吗？

### ISSUE THREAD

**Issue by k2y1982** [dotnetcore/FastGithub#23]
开启后FastGithub不能关闭是吗？

**Comment by xljiulang** [comment]
不能关闭。

**Comment by k2y1982** [comment]
能osx的打包成一个app吗？我一推出别的终端程序的时候，就会把FastGithub一起关闭了。

**Comment by xljiulang** [comment]
这个不会，你可以提osx平台的 app包装 pr

**Comment by k2y1982** [comment]
这个我也不会，Xcode太大了。十几个g，还要证书什么的，都没有。。。。不是很了解Xcode的开发流程，见谅。

**Comment by xljiulang** [comment]
你可以部署在局域网其它电脑上，比如windows，然后你macOS共享

**Comment by k2y1982** [comment]
你是说找台常开的电脑运行，然后下面的客户机dns指向那台电脑的IP？还是代理指向那台电脑的IP？端口号为80？

**Comment by k2y1982** [comment]
谢谢了。已经弄好了。走的dns，客户机把证书安装一下即可。
