### ISSUE TITLE
能否添加修复Google翻译的功能

### ISSUE THREAD

**Issue by djpangxie** [dotnetcore/FastGithub#230]
众所周知，谷歌翻译在9月底退出了中国，这给我们这些英语不好的人浏览外文网页带来不便。
论坛中的大佬们倒是出了不少解决方案：https://www.52pojie.cn/thread-1709842-1-1.html
其实就是搜寻还能使用且没被墙的IP地址，可不可以直接给FastGithub添加这个功能啊？

**Comment by EzrealJ** [comment]
不能、readme已经声明 fastgithub不具备“翻墙”功能，也没有相关的计划。

**Comment by djpangxie** [comment]
不是，这个修复不需要翻墙啊？它是搜寻境外没有被墙的Google翻译的IP地址。

**Comment by EzrealJ** [comment]
**不会将这个扫描过程添加到fastgithub**。换言之，FG只对公开dns返回的ip列表进行测速选优。

目前已知translate.google.cn是可访问状态(虽然它不提供服务)，FG为它提供选优链接优化，但无法识别能够提供服务的节点

已知translate.google.com不可访问，但FG不会对任何其做任何区别于其它站点的特殊优化


但如果有【合法】的translate.google.com的镜像服务，可以【自行】编辑配置文件将其映射给translate.google.com

**Comment by djpangxie** [comment]
好吧，那只能分开使用了。
