### ISSUE TITLE
使用FastGithub之后，vscode无法安装插件，报错 error while fetching extensions.XHR failed

### ISSUE THREAD

**Issue by JamesBrosy** [dotnetcore/FastGithub#237]
**Bug描述**
使用FastGithub之后，vscode无法安装插件，报错 error while fetching extensions.XHR failed
live.login.com也无法登录

**重现步骤**
- 我尝试通过在vscode中设置http.proxy为http://127.0.0.1:38457
  没有用，所以我把fastgithub服务关闭，重启ubuntu，也没用
- 我的ubuntu本身存在clash代理服务，但是我安装clash并设置clash服务时，并没出现过这种问题
- 我使用fastgithub时，clash代理是关闭的
- 似乎FastGithub影响了其他地方
 
**软件信息**
 - 操作系统: ubuntu22.04
 - FastGithub： v2.1.4

**Comment by JamesBrosy** [comment]
– 我现在又能使用插件搜索功能了，微软账号也能登进去了。出现上面问题的是微软账号无法登上。现在不知明原因，又能登上去了。。。

**Comment by GodfatherPacino** [comment]
我也出现了相同的问题

**Comment by GodfatherPacino** [comment]
请问有解决方案吗

**Comment by JamesBrosy** [comment]
> 请问有解决方案吗

就当做正常现象就行了，微软的这些域名似乎和特定的dns相关联。开代理的时候经常出现这种问题。不过关掉基本上就没什么事了
