### ISSUE TITLE
Invalid response received with code ServerFailure & unexpected end of stream

### ISSUE THREAD

**Issue by JamesBrosy** [dotnetcore/FastGithub#238]
**Bug描述**
![1](https://user-images.githubusercontent.com/96739684/204327638-8627a6b3-6996-4816-8ca0-a5ee1828e359.PNG)
![2](https://user-images.githubusercontent.com/96739684/204327657-5e05997c-909a-4df5-9e0c-ae0e6859bbbf.PNG)

- 出现这些问题大部分时候能正常使用github，但是也有时候不能正常使用github
- 不能使用的话，关闭fastgithub再等会再打开又能使用了，不明原因

**软件信息**
 - 操作系统: win10-x86
 - FastGithub： v2.1.4

**Comment by bicijinlian** [comment]
我的也一直这样，不知道怎么解决呀

**Comment by JamesBrosy** [comment]
> 这个软件是不是不更新了呀？开发者边车也说不更新了。不知道怎么访问Github了
> 

应该是的，偶尔能用，不伤大雅😂
