### ISSUE TITLE
一般80端口都会被占用，能自己修改一个端口吗？

### ISSUE THREAD

**Issue by doneself** [dotnetcore/FastGithub#24]
使用说明
运行FastGithub，然后浏览器访问 http://127.0.0.1 或 https://127.0.0.1 或其它ip进入Dashboard

是不是可以换个默认端口。

**Comment by k2y1982** [comment]
setting.json里没有看到改80的地方，同问此问题。

**Comment by xljiulang** [comment]
不能修改，因为fastgithub要模拟成github，你改了浏览器还是请求到80或者443

**Comment by doneself** [comment]
那就没办法了。

**Comment by xljiulang** [comment]
目前80端口是没有多少意义的，因为现在的网站几乎全部是https

**Comment by xljiulang** [comment]
Dashboard和反向代理共享端口，80不行，你可以访问https://127.0.0.1
