### ISSUE TITLE
功能添加建议

### ISSUE THREAD

**Issue by SpongeBobsnanny** [dotnetcore/FastGithub#244]
能否让它设置一下开机自启动，谢谢😍

**Comment by XYZliang** [comment]
有几个简单的方法，对于windows：

windows开始菜单有个启动文件夹，系统启动后，会自动打开启动文件夹里的东西，就是360老喜欢把里面的东西当病毒，记得加信任。
1. 你可以复制fastgithub.exe并在这个启动文件夹下创建一个快捷方式。
2. 编写一个BAT脚本，内容为`E:\fastgithub_win-x64\fastgithub.exe start`并放到启动文件夹里来开机自动运行服务模式（E:\fastgithub_win-x64替换为你自己的路径）
3. 利用一些管理开机项目的软件，把fastgithub添加进去就是

macOS也是差不多的，在启动项里直接添加就行，或者写脚本，脚本添加到启动项

**Comment by SpongeBobsnanny** [comment]
谢谢啦
