### ISSUE TITLE
Linux 启动FastGithub显示fastgithub: command not found

### ISSUE THREAD

**Issue by luckyEason** [dotnetcore/FastGithub#249]
eason@dianmanpc:~/fastgithub_linux-x64/fastgithub_linux-x64$ ls
LICENSE  README.html  README.md  appsettings  appsettings.json  dnscrypt-proxy  fastgithub
eason@dianmanpc:~/fastgithub_linux-x64/fastgithub_linux-x64$ sudo ./fastgithub start
sudo: ./fastgithub: command not found

怎么办

**Comment by nickxsc** [comment]
chmod 777 fastgithub  试试看

**Comment by lucktu** [comment]
我在ubuntu下装docker，docker里面装ubuntu，再在里面装fastgithub，工作非常好，但是，同样是 docker 下的 openwrt，就不可用了，与你的错误一样。

**Comment by luckyEason** [comment]
我将fastgithub的地址改成了完整地址，fastgithub工作非常好
