### ISSUE TITLE
软件功能失效

### ISSUE THREAD

**Issue by L-Super** [dotnetcore/FastGithub#250]
**Bug描述**
最近打开FastGithub.UI.exe，都没法使用，仍然打不开GitHub，且流量那里没有波动，可能功能失效了

**软件信息**
 - 操作系统: Win11
 - FastGithub：v2.1.4

**Comment by Vogadero** [comment]
瞎扯🤣

**Comment by L-Super** [comment]
那为什么用不了了呢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月23日(星期五) 上午10:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dotnetcore/FastGithub] 软件功能失效 (Issue #250)





 
瞎扯🤣

**Comment by Grey-Wind** [comment]
我这里仍能正常使用

**Comment by Vogadero** [comment]
> 我这里仍能正常使用

➕1️⃣
