### ISSUE TITLE
ssh似乎用不了

### ISSUE THREAD

**Issue by taooceros** [dotnetcore/FastGithub#28]
开了FastGithub之后似乎无法使用ssh进行git操作了

**Comment by xljiulang** [comment]
ssh无法（多域名）反向代理，所以fastGithub只支持http和https协议，git操作请使用https

**Comment by xljiulang** [comment]
不过貌似可以通过tls握手拿到SNI，从而做到多域名的ssh代理

**Comment by luolingchun** [comment]
使用ssh时仍然使用原来的dns解析是否可行？

**Comment by xljiulang** [comment]
@luolingchun dns是最先工作的。

**Comment by xljiulang** [comment]
或者可以设计为域名替换？git@ssh.github.com、git@ssh.xxx.com这样子？ssh子域名解析为主域名ip
