### ISSUE TITLE
最近一段时间（半个月）相应速度明显提高

### ISSUE THREAD

**Issue by xiatian12345** [dotnetcore/FastGithub#308]
**Bug描述**
2023-09-06T19:47:41.4029060+08:00 [WRN]
FastGithub.HttpServer.RequestLoggingMiddleware
GET https://alive.github.com/_sockets/u/51563875/ws responded 101 in 192773.2071 ms
System.OperationCanceledException: The operation was canceled.

**软件信息**
 - 操作系统: mac 13.2.1 (22D68)
 - FastGithub：v2.1.4

**Comment by demodeom** [comment]
今天测试 UbutnuDesktop22.04操作系统， 网页响应速度很快， 感谢大佬的努力

**Comment by demodeom** [comment]
网页版、网页登陆、资源下载、Git 均正常使用
