### ISSUE TITLE
[Feature request] Non-standard local DNS port support

### ISSUE THREAD

**Issue by sky96111** [dotnetcore/FastGithub#34]
In many cases 53 port are used by other services (e.g. OpenWrt DNS service and Fedora systemd-resolve)
They use dnsmasq to provide a local DNS services, which both support non-standard DNS port upstream query.
I think it would be better to provide an option to config DNS port, there are many benefits:
1. It can be deployed on an OpenWrt router and use dnsmasq rules to specify GitHub domains to use FastGiHub
2. Fedora Ubuntu and more and more distributions use build-in systemd-resolver in default, this can avoid disabling systemd-resolver unnecessarily.

在很多场合53端口会被其他服务占用（比如OpenWrt提供的DNS服务和Fedora自带的systemd-resolve）
它们使用了dnsmasq来提供本地DNS服务，并且都支持向非标准端口上游查询
我认为添加一个配置选项来指定监听端口在一些场合会很不错，比如
1. 把服务部署在OpenWrt路由器上，使用dnsmasq规则来指定GitHub使用FastGithub服务
2. Fedora、Ubuntu和越来越多的发行版默认使用内建的systemd-resolver来解析DNS，此举能避免不必要地关闭systemd-resolver服务

**Comment by xljiulang** [comment]
是可以实现，但是不知道这么做之后不见得带来方便：
FastGithub支持除github之后其它相关域名，且域名支持*号通配，符合的域名才走FastGithub的反向代理，不如把FastGithub当作标准dns，然后指定上游到dnsmasq，这样之后，FastGithub不感兴趣的域名都会经过dnsmasq。

**Comment by sky96111** [comment]
> 是可以实现，但是这么做之后不见得带来方便：
> FastGithub支持除*.github之外其它相关域名，且域名支持*号通配，符合的域名才走FastGithub的反向代理，不如把FastGithub当作标准dns，然后指定上游到dnsmasq，这样之后，FastGithub不感兴趣的域名都会经过dnsmasq。

我确实也发现除了GitHub配置中也维护了v2和onedrive之类的网站，但权衡下其他的问题我觉得写一份规则也能接受
遇到了个棘手的问题，当前的程序逻辑是：一旦53端口被占用，程序将无法启动，但是并不是所有场合53端口都能被安全禁用的。OpenWrt中配置dnsmasq非标准端口会导致DHCP不下放DNS地址，彻底禁用则无法解析本地主机名。同时我也在使用KVM虚拟机，dnsmasq作为必要的依赖用于提供一个标准端口的DNS查询
而且部署在本机的服务在nslookup一个本地主机名的时候会出现可观的查询延迟，这个现象我觉得在分流阶段就丢给dnsmasq可能会更好？

**Comment by xljiulang** [comment]
如果是这样子，提供可配置的dns端口是可以的。

**Comment by sky96111** [comment]
感谢！

**Comment by xljiulang** [comment]
该功能已完成开发。

**Comment by sky96111** [comment]
看来在路由器上轻松部署还是我想多了…
得关掉路由器lighttpd释放80端口，再套一个Caddy反代分流路由器LuCI管理界面和FG的反向代理网页…多重套娃了😂

**Comment by xljiulang** [comment]
80不是必须的，443可用就不影响，路由器有dhcp，配置dns 值为自身ip是不是就可以了
