### ISSUE TITLE
May i set dashboard listen port by config file?

### ISSUE THREAD

**Issue by vosdbk** [dotnetcore/FastGithub#37]
FastGithub listen port 80 for dashboard by default, but sometime this port is used for other app. So may i set dashboard listen port by config file?
FastGithub默认为 `dashboard `侦听 `80` 端口，但有时此端口用于其他应用程序。所以能否通过配置文件设置 `dashboard` 侦听端口?

**Comment by xljiulang** [comment]
FastGithub是反向代理，不管有没有dashboard，443是必须的80是可选的。
如果dashboard用其它端口，只会占用更多端口。

**Comment by vosdbk** [comment]
I already use nginx for reverse proxy in LAN, so i search for the way to custom config FastGithub's port. Could you consider this suggestion in next stable version?
我已经在LAN中使用nginx作为反向代理，故寻求自定义配置FastGithub端口的方法。您能在下一个稳定版中考虑一下这个建议吗?

**Comment by xljiulang** [comment]
FastGithub=nginx+dns，所以它和nginx是完全冲突的，建议你把FastGithub安装到局域网其它设备上，然后修改你本机的主dns为安装FastGithub的设备的ip，有关局域网部署详细信息，请在安装FastGithub之后访问https://localhost进入dashboard查看指南。

**Comment by vosdbk** [comment]
thx a lot.
非常感谢.
