### ISSUE TITLE
mac os上 怎么运行？

### ISSUE THREAD

**Issue by sunyazhou13** [dotnetcore/FastGithub#38]
请教一下  mac上如何运行,下载后发现

![Snipaste_2021-08-24_07-51-05.jpg](http://ww1.sinaimg.cn/large/003vs6Vrly1gtrjnvyw2ij607m05st8s02.jpg)

**Comment by xljiulang** [comment]
这个版本打包忘记设置可执行权限了
你需要先设置可执行权限
```
cd FastGithub_osx-x64
chmod 777 ./FastGithub
chmod 777 ./dnscryptproxy/dnscrypt-proxy
```

**Comment by sunyazhou13** [comment]
它们是脚本是吗？

**Comment by xljiulang** [comment]
在终端运行

**Comment by sunyazhou13** [comment]
> 在终端运行

ok 好的 谢谢 已经成功执行了 建议  写个 简单的文档  告知一下 各位  cd 到  这个目录 然后执行  ./FastGithub

**Comment by xljiulang** [comment]
不用的，我zip包里修复就可以，就不需要这么设置可执行权限了
