### ISSUE TITLE
win10 wls2与主机dns冲突

### ISSUE THREAD

**Issue by jghuangcn** [dotnetcore/FastGithub#4]
win10 下安装 wsl ubuntu docker，启用docker后会有问题，linux的shell会进不去，docker启动不了。docker启动后，再用fastgithub有时是好的。

**Comment by xljiulang** [comment]
有何异常？

**Comment by jghuangcn** [comment]
在WIN10下启用fastgithub服务后，docker就运行不了了，ubuntu 20.04 shell也进不了。

**Comment by xljiulang** [comment]
我以为你在docker下运行FastGithub软件不成功，FastGithub不会影响到windows系统的稳定性呢，dns服务占用了udp的53端口而已。要不你试试使用网络调度助手监听udp53端口试试，看会不会影响到wsl2

**Comment by LGinC** [comment]
dns服务占用53端口后wsl 2 就跑不起来了

**Comment by xljiulang** [comment]
我在win10上无法复现，wsl2能正常运行。问题先关闭，待有人遇到同样问题再开启。
