### ISSUE TITLE
Create installation scripts for submission to winget-pkgs and chocolatey

### ISSUE THREAD

**Issue by VAllens** [dotnetcore/FastGithub#41]
It is recommended to create installation scripts for submission to winget-pkgs and chocolatey. :)
https://github.com/microsoft/winget-pkgs
http://chocolatey.org/packages

**Comment by EzrealJ** [comment]
The following is translated by Google

Hello, there is currently no plan to distribute through any package management tools on any platform. Thank you for your proposal. If we plan to distribute through channels other than github, your proposal will be considered.
