### ISSUE TITLE
可不可以只用dns不用代理

### ISSUE THREAD

**Issue by szmcdull** [dotnetcore/FastGithub#43]
安装证书总感觉不安全

**Comment by xljiulang** [comment]
dns只是反向代理的铺垫，反向代理才是根本

**Comment by chengyiqun** [comment]
真正的问题是SNI阻断, 而不是dns解析问题. 加dnsproxy是目的是保证解析无污染的dns, 但是是不够的, 还要解决"连接已重置". SNI阻断是建立https连接前的头信息里可以被墙探测到你访问的目标网站是github, 而证书的目的就是在于伪造https请求握手阶段的SNI头.(个人理解, 可能有表述不准确的地方, 如有误请指正)

**Comment by xljiulang** [comment]
正解

**Comment by szmcdull** [comment]
好想有个驱动，可以过滤不正常的rst包，比如收到reset包之后延时个10s，如果还没有收到syn，才向用户层发送连接断开的事件

**Comment by xljiulang** [comment]
@szmcdull 这个还真有，但是rst包是表象，rst之后，就算过滤rst，之后连接的数据也会被丢弃。
