### ISSUE TITLE
建议在国内平台搞一份镜像

### ISSUE THREAD

**Issue by ddyllen-z** [dotnetcore/FastGithub#46]
GitHub本来很难打开，下载文件又慢，你这用来加速的又放在GitHub上面，这不是有点矛盾吗？

**Comment by xljiulang** [comment]
如果国内有这样的解决方案，那自然喜大奔波，甚至github也免了，然后这个工具也不需要了。关键是没有啊。

**Comment by ddyllen-z** [comment]
@xljiulang 是说放一个可以方便快速下载到发布文件的地方。

**Comment by xljiulang** [comment]
qq群不是吗

**Comment by ddyllen-z** [comment]
行吧。

**Comment by chengyiqun** [comment]
gitee上放个release镜像也好吧.
