### ISSUE TITLE
卸载了不能上网了，改了什么系统文件吗？

### ISSUE THREAD

**Issue by thicktao** [dotnetcore/FastGithub#54]

**Comment by xljiulang** [comment]
只修改了 dns，你看看dns如果是127.0.0.1的话去掉就行

**Comment by thicktao** [comment]
正想说删除	127.0.0.1       localhost.lodop.net 这个就可以了，删除了 github这一下纹丝不动了--！

**Comment by xljiulang** [comment]
v2.0版本将不修改系统dns配置，敬请关注
