### ISSUE TITLE
关闭软件后，无法删除 WinDivert64.sys 文件

### ISSUE THREAD

**Issue by myesn** [dotnetcore/FastGithub#58]
操作步骤：
1. 打开 exe 软件，然后关闭它
2. 删除整个目录，然后就会提示 `WinDivert64.sys`  文件无法删除 

![image](https://user-images.githubusercontent.com/18598579/134310188-11e5dadd-7cd1-4c00-86ad-4783b316e450.png)
![image](https://user-images.githubusercontent.com/18598579/134310566-99ba2547-f16f-4c5f-a176-0a1d63713605.png)

**Comment by xljiulang** [comment]
重新打开，然后ctrl加c关闭，再删除试试

**Comment by myesn** [comment]
还是不行，重启了也删除不掉

**Comment by myesn** [comment]
录制了一个 GIF：

![dashboard](https://user-images.githubusercontent.com/18598579/134355758-90a0ef09-c685-4df7-9d84-f693c1c2e7ac.gif)

**Comment by xljiulang** [comment]
重启设备之后可以删除。
或者执行
WinDivert1.4
sc stop 
sc delete WinDivert1.4

这是WinDivert的文档，我也还没有实验，如果生效，我将加入手动卸载功能

**Comment by myesn** [comment]
现在可以删除了😊，可能是我重启电脑之后才可以的吧。

至于 `WinDivert1.4` 服务，我电脑上并未找到

![image](https://user-images.githubusercontent.com/18598579/134458248-79770a9d-897c-4b15-980b-9d20830611dd.png)
