### ISSUE TITLE
图片显示异常

### ISSUE THREAD

**Issue by Knn120** [dotnetcore/FastGithub#59]
win7 64位   chrome 91.0.4472.106（正式版本） （64 位）
FastGithub 2.0.0-beta3

**Comment by xljiulang** [comment]
win7很多情况下会出现在tls握手时，系统支持的加密算法和服务器支持的密码算法没有交集，导致此类服务器提供的网站无法加速。需要 win10才能完整加速

**Comment by zlay0701** [comment]
加群 下载最新版本再试
