### ISSUE TITLE
下载 2.0版本 这是github返回代码 101 的意思 ，浏览器端没有速度？

### ISSUE THREAD

**Issue by sgf** [dotnetcore/FastGithub#62]
**Bug描述**
Bug的详细描述内容

![image](https://user-images.githubusercontent.com/2557696/134618434-39612bbb-d964-4d70-b1fd-e0a22db0b538.png)

![image](https://user-images.githubusercontent.com/2557696/134618486-1ac15430-2a5b-404f-9450-6449915c6dad.png)

**重现步骤**
1.  xxx
2.  yyy
3.  zzz
 

**软件信息**
 - 操作系统: [e.g. win10-x64]
 - FastGithub： [e.g.  v1.2.0]

**Comment by sgf** [comment]
经过二十次尝试后成功下载 2.0版本。

**Comment by xljiulang** [comment]
101是协议转换哈，像升级为websocket就用到这个状态状态码，和下载失败没有关系。
