### ISSUE TITLE
[question]关闭git的证书验证是否有安全风险

### ISSUE THREAD

**Issue by dyxang** [dotnetcore/FastGithub#64]
如标题，是否对平常普通使用有安全风险的影响

**Comment by xljiulang** [comment]
如果不用git来提交国家级核心代码，估计没人想钓你的鱼

**Comment by dyxang** [comment]
> 如果不用git来提交国家级核心代码，估计没人想钓你的鱼

感谢，对Git不是很了解。
先前对于关闭认证的认知是相当于服务器ssh敞开让人来挖矿的程度

**Comment by xljiulang** [comment]
ssl证书和ssh没有关系，ssh只有加密没有证书认证，关闭ssl证书认证的https，就和ssh差不多，只能保证传输加密，不保证请求的目标是预期的目标，可能是钓鱼的目标。但是被钓鱼的前提是你的传输层被中间人攻击了
