### ISSUE TITLE
指定网址自动跳转到该项目主页

### ISSUE THREAD

**Issue by dyxang** [dotnetcore/FastGithub#65]
**Bug描述**
访问指定网址会自动跳转到该项目地址

**重现步骤**
1.  访问 https://aka.ms/PowerToysOverview_ImageResizer
2.  302跳转到该地址
 

**软件信息**
 - 操作系统:win10-x64
 - FastGithub：v2.0.2

**好像没用的Log前后文**
```
2021-10-04T17:33:53.0899809+08:00 [INF]
FastGithub.HttpServer.RequestLoggingMiddleware
GET https://aka.ms/PowerToysOverview_ImageResizer responded 302 in 0.0323 ms

2021-10-04T17:33:53.9307060+08:00 [INF]
FastGithub.HttpServer.RequestLoggingMiddleware
GET https://github.com/dotnetcore/fastgithub responded 200 in 836.1751 ms
```

**Comment by xljiulang** [comment]
你试试ping这个域名，应该是不正确地返回了127.0.0.1的ip。产生这个问题还没有准确的原因，方便把你dns设置的值贴出来吗

**Comment by dyxang** [comment]
> 你试试ping这个域名，应该是不正确地返回了127.0.0.1的ip。产生这个问题还没有准确的原因，方便把你dns设置的值贴出来吗

```
正在 Ping aka.ms [127.0.0.1] 具有 32 字节的数据:
来自 127.0.0.1 的回复: 字节=32 时间<1ms TTL=128
········
127.0.0.1 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 0ms，最长 = 0ms，平均 = 0ms
```
DNS
```
218.104.111.122
218.104.111.114
```

**Comment by xljiulang** [comment]
fg的配置文件你有改了什么吗？重启fg问题还存在吗？

**Comment by xljiulang** [comment]
方便的话，抓一段网络数据包：关闭fastgithub，启动wireshark开始抓包，cmd输入ipconfig /flushdns，然后重新ping那个域名，然后停止抓包。

**Comment by dyxang** [comment]
> fg的配置文件你有改了什么吗？重启fg问题还存在吗？

存在，重启电脑/更换网络依旧存在

> 启动wireshark开始抓包

具体需要哪些信息呢

**Comment by xljiulang** [comment]
你加入fg的qq群，我在群里协助抓包

**Comment by dyxang** [comment]
## 问题原因
使用的公共DNS本身问题
## 解决方法

1. 使用别的 DNS 如 114，然后清空 DNS 缓存（WIndows CMD > `ipconfig /flushdns`）
2. 使 fastgithub 代理，在 fastgithub 安装文件的 appsettings 文件夹下新建形如以下的 appsettings.aka.json 文件
```
  {
    "FastGithub": {
      "DomainConfigs": {
        "aka.ms": {
          "TlsSni": true
        }
      }
    }
  }

```
