### ISSUE TITLE
macOSX 使用2.0.2无法下载 release包

### ISSUE THREAD

**Issue by jingliancui** [dotnetcore/FastGithub#68]
**Bug描述**
因为fastgithub更新了新版本2.0.3，所以尝试到GitHub网站下载新的release包。请看重现步骤。

**重现步骤**
1.  打开release页面

2.  点击osx包的链接
<img width="1259" alt="issue1" src="https://user-images.githubusercontent.com/16309962/136643840-97fee61d-b8ba-4233-b68f-214e9cd6b4ad.png">

3.  显示错误
<img width="1274" alt="issue2" src="https://user-images.githubusercontent.com/16309962/136643844-2ef0e4dd-208c-45fd-ba3b-64493827bcc7.png">

**软件信息**
 - 操作系统: [mac m1]
 - FastGithub： [v2.0.2]

其他信息：
应该是代理导致的，当将fastgithub关闭并去掉代理后可以下载。

**Comment by xljiulang** [comment]
https://github.com/dotnet/aspnetcore/issues/37421
