### ISSUE TITLE
检测到nexus.xxxx.com可能遭遇了dns污染

### ISSUE THREAD

**Issue by lshz0088** [dotnetcore/FastGithub#72]
**Bug描述**
```
2021-10-18T15:23:35.1865770+08:00 [WRN]
FastGithub.HttpServer.HttpReverseProxyMiddleware
检测到nexus.xxxx.com可能遭遇了dns污染
```

**重现步骤**
`nexus.xxxx.com`是一个maven私服，公司内部配有dns转发到内网的nginx服务器ip。外网dns转发到对外的路由器上，通过NAT访问nginx服务器。

开启了`fastgithub`后无法拉取maven镜像，提示dns遭到了污染。

不知如何解决？

直到关闭了`fastgithub`，将配置的三个代理项反向勾选，重启电脑才恢复

**软件信息**
 - 操作系统: macOS 10.15.7 
 - FastGithub: v2.0.4

**Comment by xljiulang** [comment]
你试试 自动代理，而不是手动代理
