### ISSUE TITLE
重新考虑UI项目的目标平台

### ISSUE THREAD

**Issue by EzrealJ** [dotnetcore/FastGithub#77]
**重新考虑UI项目的目标平台**
 参考.NET Framework的产品生命周期，UI项目的目标平台net45已于2016 年 1 月 12 日停止支持，可以考虑以仍在支持的更高版本或最新版本的.NET Framework来构建，甚至准备以net6为目标构建

**Comment by xljiulang** [comment]
虽然停止支持了，但低版本的可以在高版本运行时环境运行。反过来，如果构建时选择的编译版本过高，客户端可能就要自己安装高版本的.net Framework。至于.net6构建，这完全没有必要，因为只是把软件的体积从1M变成70M。
