### ISSUE TITLE
提议支持win7

### ISSUE THREAD

**Issue by fawdlstty** [dotnetcore/FastGithub#78]
**Bug描述**
2.0.4及以前版本在win7下运行fg异常，频繁出现无法访问的情况，重启fg或者关闭fg恢复正常
2.0.5不支持win7

**重现步骤**
1.  运行2.0.4及以前版本
2.  访问github
3.  过几分钟到十几分钟
4.  访问github
 

**软件信息**
 - 操作系统: win7sp1 (7601)
 - FastGithub： [e.g.  v2.0.0] all

**Comment by xljiulang** [comment]
目前无法解决win7遇到的tls1.2问题 ,你可以试试2.0.4版本并参考https://docs.microsoft.com/zh-cn/sharepoint/troubleshoot/administration/authentication-errors-tls12-support

**Comment by EzrealJ** [comment]
## 提出反对

### 🧐Windows 7 支持于 2020 年 1 月 14 日终止[参考](https://support.microsoft.com/zh-cn/windows/windows-7-%E6%94%AF%E6%8C%81%E4%BA%8E-2020-%E5%B9%B4-1-%E6%9C%88-14-%E6%97%A5%E7%BB%88%E6%AD%A2-b75d4580-2cc7-895a-2c9c-1466d9a53962)

它仍然有众多的用户，但它必然会被取代，(就像曾经的Windows XP)；我们也应该考虑放弃对它的支持。

即使v2版本不再支持WIndows 7，依然可以选择将v1版本部署在网络链接可达的仍受支持的OS上作为私有的DNS服务器来间接的支持其它不可使用v2版本的设备，这应该是一个不错的解决方案。

是时候放弃Windows 7了；海内存知己，天涯若比邻；向您推荐已经成熟的Windows 10.

**Comment by xljiulang** [comment]
已经不支持win7

**Comment by liaoxuewei** [comment]
> ## 提出反对
> ### Windows 7 支持于 2020 年 1 月 14 日终止[参考](https://support.microsoft.com/zh-cn/windows/windows-7-%E6%94%AF%E6%8C%81%E4%BA%8E-2020-%E5%B9%B4-1-%E6%9C%88-14-%E6%97%A5%E7%BB%88%E6%AD%A2-b75d4580-2cc7-895a-2c9c-1466d9a53962)
> 它仍然有众多的用户，但它必然会被取代，(就像曾经的Windows XP)；我们也应该考虑放弃对它的支持。
> 
> 即使v2版本不再支持WIndows 7，依然可以选择将v1版本部署在网络链接可达的仍受支持的OS上作为私有的DNS服务器来间接的支持其它不可使用v2版本的设备，这应该是一个不错的解决方案。
> 
> 是时候放弃Windows 7了；海内存知己，天涯若比邻；向您推荐已经成熟的Windows 10.

是什么原因不能支持呢？我认为否认win7还很大的市场，win10/11都很多稳定性问题，win7跟win10、win11没有什么区别，只是微软要赚钱而已

**Comment by xljiulang** [comment]
win7默认只支持tls1.1，这是已经淘汰的加密传输版本。

**Comment by fawdlstty** [comment]
> 是什么原因不能支持呢？

@liaoxuewei 因为出了个bug，疑似win7系统加密算法问题，导致ssl协议故障，具体表现连接了一段时间的ssl管道突然报错，提示协议格式不正确。可能的修复方式有切换ssl加密库、自动重启broker进程、或者调查实际原因找到解决方案等。如果你有时间修的话，作者就给支持win7了 :)
