### ISSUE TITLE
希望支持arm版linux系统

### ISSUE THREAD

**Issue by duping812** [dotnetcore/FastGithub#79]
**Bug描述**
目前的linux版本只试用于x64的系统，而树莓派，jetson nano等单片机则是arm版的linux，希望能提供支持，谢谢。

**重现步骤**
./fastgithub 报错
bash: ./fastgithub: cannot execute binary file: Exec format error

**软件信息**
 - 操作系统: ubuntu 18 on jetson nano 4G
 - Linux ping-jetson 4.9.253-tegra #1 SMP PREEMPT Mon Jul 26 12:13:06 PDT 2021 aarch64 aarch64 aarch64 GNU/Linux
 - FastGithub：v2.0.5, linux-x64

**Comment by xljiulang** [comment]
可以支持。
当前你可以迁出代码，自己build出arm版本的。

**Comment by xljiulang** [comment]
[fastgithub_linux-arm64.zip](https://github.com/dotnetcore/FastGithub/files/7480805/fastgithub_linux-arm64.zip)
你可以试试这个，未测试。

**Comment by duping812** [comment]
谢谢，arm64版在jetson nano上测试，web浏览器可用，terminal里git clone报错
`fatal: unable to access 'https://github.com/duping812/hello-world.git/': Could not resolve proxy: http`

**Comment by duping812** [comment]
最新2.0.7版问题解决，terminal下git clone也可以了。谢谢老九

**Comment by duping812** [comment]
请问可以编译一份32位arm版的吗？树莓派3等老板子也想用一下。

**Comment by xljiulang** [comment]
您可以需要安装dotnet7.0 sdk，然后自己build

**Comment by duping812** [comment]
> 

可否提供一个简要的编译说明？
