### ISSUE TITLE
【新功能】建议增加在线更新软件版本的功能；【问题】Edge浏览器PDF下载问题

### ISSUE THREAD

**Issue by think-ya** [dotnetcore/FastGithub#81]
这个项目真的很不错，解决了国内使用GitHub的问题。
1、建议添加在线更新软件版本的功能，这样就可以随时用上作者辛苦开发的新功能了。
2、Edge浏览器打开在线的PDF文件时，会首先将文件下载到浏览器缓存中，然后在Edge中打开；当点击Edge中PDF保存按钮时，浏览器会从再次从原地址下载这个PDF文件，而不是直接将缓存中的文件另存到指定位置；这样就导致使用Edge保存正浏览的PDF文件时速度特别慢。（怀疑是不是跟代理了127.0.0.1有关，可能edge保存pdf时也是走的这个地址）

**Comment by xljiulang** [comment]
给个pdf地址看看

**Comment by think-ya** [comment]
不好意思，打扰了。我现在重现不了这个问题了，可能是我的问题。
