### ISSUE TITLE
[问题]: wsl如何使用在windows中开启的fastgithub服务

### ISSUE THREAD

**Issue by younger-1** [dotnetcore/FastGithub#83]
**问题描述**
在 windows 中安装了 fastgithub 作为服务，然后 wsl2 中使用如下命令测试 github 的可访问性
```
curl --connect-timeout 5 github.com
```
发现无法访问。有办法可以让 wsl 也使用 fastgithub 的服务吗？

**软件信息**
 - 操作系统: [Windows NT 19043]
 - FastGithub： [2.0.4]

**Comment by xljiulang** [comment]
wsl是linux系统，所以要在wsl里面安装fg的linux 版本

**Comment by xljiulang** [comment]
wsl是linux系统，所以要在wsl里面安装fg的linux 版本。
如果是wsl1，由于系统组件不全的原因fg可能无法运行，可以考虑使用Hyper-V安装完整版本的linux

**Comment by younger-1** [comment]
就是说 fg 在 windows 下没有提供给其它客户机访问的接口吗，希望能像linux那样能设置系统代理为 `http://127.0.0.1:38457` 就更方便了

**Comment by xljiulang** [comment]
windows下使用驱动拦截dns+http(s)反向代理机制，与unix的http正向代理+http(s)反向代理机制有所不同，该方案最适合windows，不需要修改系统的任何网络配置，且可以为本机所有应用提供服务，该方案的如下功能要求本机必须安装fg：
* 向系统安装驱动
* 向系统安装fg根证书

unix平台使用的正向代理方案有很多缺陷，使用它其实是无奈之举：
* 容易与其它代理冲突(2选1)
* 系统或fg意外关闭后因遗留代理配置造成主机网络瘫痪
* 部分软件不走系统配置的代理，且可能没有独立配置的接口

**Comment by xljiulang** [comment]
如果你喜欢，你可以选择1.2.x版本，此版本的方案是 自建dns服务+http(s)反向代理，且监听主机的所有IP，可以为其它客户机提供服务，只需要客户机配置dns的ip为主机的ip即可，但要求主机的所有IP的80和443端口为fg独占。

**Comment by younger-1** [comment]
感谢大佬这么及时的解答，看来还是两边都装比较方便 😸

**Comment by younger-1** [comment]
感谢大佬这么及时的解答，看来还是两边都装比较方便 :smil
