### ISSUE TITLE
最新版本不支持Win7 64位操作系统

### ISSUE THREAD

**Issue by liuweiisme** [dotnetcore/FastGithub#85]
最新版本不支持Win7 64位操作系统了？

**Comment by xljiulang** [comment]
不支持了，fg在一些win7上运行体验不好，同时win7本身也退役了。

**Comment by liaoxuewei** [comment]
> 不支持了，fg在一些win7上运行体验不好，同时win7本身也退役了。

说真的，不太认同。。。
