### ISSUE TITLE
ubuntu系统安装CA证书

### ISSUE THREAD

**Issue by duping812** [dotnetcore/FastGithub#86]
**Bug描述**
ubuntu系统安装CA证书需要crt格式，而目前的代码里只有cer格式。其实他们都是纯文本格式，只是后缀不同。

建议增加fastgithub.crt文件，或在安装说明里解释一下。

**重现步骤**
$ sudo cp cacert/fastgithub.cer /usr/local/share/ca-certificates/fastgithub.crt
$ sudo update-ca-certificates
 
**软件信息**
 - 操作系统: ubuntu 18
 - FastGithub：v2.0.5

**Comment by xljiulang** [comment]
osx是cer后缀，win和centos其实crt或cer都可以，ubuntu是不是两种后缀也可以呢?

**Comment by duping812** [comment]
> osx是cer后缀，win和centos其实crt或cer都可以，ubuntu是不是两种后缀也可以呢?

ubuntu只认crt，我试过cer无法安装。
[https://ubuntu.com/server/docs/security-trust-store](https://ubuntu.com/server/docs/security-trust-store)

**Comment by xljiulang** [comment]
linux主要发行版的证书自动安装已集成到fg

```
Updating certificates in /etc/ssl/certs...
1 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
```

**Comment by duping812** [comment]
是在下一版里实现的？我刚试了2.0.7，还是提示根据linux发型版手动安装证书

**Comment by xljiulang** [comment]
下个版本才有

**Comment by westfly** [comment]
基于libcurl的库可以设置环境变量绕过去

```shell
export CURL_CA_BUNDLE=/etc/ssl/certs/fastgithub.cer
```
