### ISSUE TITLE
python requests error on centos7

### ISSUE THREAD

**Issue by shungo2020** [dotnetcore/FastGithub#88]
**Bug描述**
[ERR]
Microsoft.AspNetCore.Server.Kestrel
Connection id "0HMD7VE0TQ5CP", Request id "0HMD7VE0TQ5CP:00000002": An unhandled exception was thrown by the application.
System.ArgumentException: The parameter 'host' cannot be an empty string.
   at System.Net.DnsEndPoint..ctor(String , Int32 , AddressFamily )
   at System.Net.DnsEndPoint..ctor(String , Int32 )
   at FastGithub.HttpServer.HttpProxyMiddleware.GetTargetEndPointAsync(HostString host)
   at FastGithub.HttpServer.HttpProxyMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

**重现步骤**
1.  run fastgithub
2.  export http_proxy=http://127.0.0.1:38457
export https_proxy=http://127.0.0.1:38457
3.  run python script:
`url = 'https://raw.githubusercontent.com/huggingface/datasets/1.15.1/datasets/glue/glue.py'
    response = requests.request(method="HEAD", url=url)
    print(response.request.headers)`

wget可以正常工作

**软件信息**
 - 操作系统: centos7
 - FastGithub：v2.0.7

**Comment by xljiulang** [comment]
流行的工具,wget、curl等都是没有问题哦，产生这个异常的本质是你是的python请求没有提交必须的host头。其它流行的编程语言的HttpClient，在不设置host的情况下，都会默认将uri的host值自动设置到http请求头的host，可能是python默认下就没有这个自动设置吧？see https://pretagteam.com/question/missing-host-header-in-http-requests-from-the-requests-python-library

**Comment by shungo2020** [comment]
强制加上host头也不行，报的错误也是一样的：
url = 'https://raw.githubusercontent.com/huggingface/datasets/1.15.1/datasets/glue/glue.py'
headers = {"Host": "raw.githubusercontent.com"}
response = requests.request(method="GET", url=url, headers=headers)
print(response.request.headers)

但是把url改成http就可以
url = 'http://raw.githubusercontent.com/huggingface/datasets/1.15.1/datasets/glue/glue.py'

**Comment by xljiulang** [comment]
那你可能需要使用tcpdump抓一下包，然后发来我分析一下

**Comment by shungo2020** [comment]
[python.zip](https://github.com/dotnetcore/FastGithub/files/7537360/python.zip)
转了lo上的包，帮看下

**Comment by shungo2020** [comment]
好像是python这个http库用的是1.0的proxy 所以connect里面没带Host
https://stackoverflow.com/questions/43380862/requests-library-force-use-of-http-1-1-on-https-proxy-connect

**Comment by xljiulang** [comment]
```
CONNECT raw.githubusercontent.com:443 HTTP/1.0

HTTP/1.1 500 Internal Server Error
Content-Length: 0
Connection: close
Date: Mon, 15 Nov 2021 09:09:31 GMT
Server: Kestrel
```
你更新库吧，这个还是发http1.0的，而且不符合connect协议

**Comment by xljiulang** [comment]
请求http可以，是因为http代理可以不走conncet协议，fg直接反代。但https代理，必须是connect

**Comment by xxcdd** [comment]
我遇到了同样的问题，使用https://github.com/python/cpython/pull/8305/files这个pr可以解决
