### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by heku** [dotnetcore/FastGithub#89]
你好，
首先感谢你们开发了这个小工具，确实有时候能提速github的访问，解决了一些麻烦。
我使用过程中没有发现有类似的【卸载】的选项，或许这只是一个绿色工具，但我过了下源码的时候，看到一些写注册表的操作，这些注册表信息应该也能提供某个操作来清理掉（不只注册表，如果还有其他文件或更改的话，也应该能提供相应的恢复的的操作），这样在不使用或者不再需要这个工具的时候，可以彻底清理掉相关设置。
谢谢！

**Comment by xljiulang** [comment]
绿色的，直接删除就可以了。注册表配置也只是针对本程序的，不影响到其它。
