### ISSUE TITLE
flutter pub get异常

### ISSUE THREAD

**Issue by gohopo** [dotnetcore/FastGithub#92]
**Bug描述**
pub是flutter的包管理工具，支持从github上下载包。但是在使用FastGithub后，不能正常下载github上的包。
浏览器和本地git客户端都能正常使用和访问github。

![QQ截图20211123102504](https://user-images.githubusercontent.com/8192266/142963901-b6588f98-9e81-471e-ae5a-958544088716.png)

**重现步骤**
1.  在flutter项目中，以github方式引用包
![QQ截图20211123102547](https://user-images.githubusercontent.com/8192266/142963958-a42ab55e-ae9b-4b55-a3b8-c2ee55155e16.png)

2.  执行pub get操作
 

**软件信息**
 - 操作系统: win11-x64
 - FastGithub： v2.1.0

**Comment by xljiulang** [comment]
fastgithub不支持git协议，只支持ssh、http和https协议，请改成ssh或https来请求github

**Comment by gohopo** [comment]
@xljiulang 
改成https可以了 谢谢

**Comment by xljiulang** [comment]
https://github.com/dotnetcore/FastGithub/commit/9e559c36fedd089c05ee6a2592806b5102d4f198
已增加git协议代理支持
