### ISSUE TITLE
windows-x64版本FastGithub在关闭之后浏览器无法上网

### ISSUE THREAD

**Issue by rocinant** [dotnetcore/FastGithub#93]
如题，直接cmd退出之后，浏览器无法正常上任何网站。包括电脑重启，无法恢复域名解析。

**Comment by xljiulang** [comment]
fg哪个版本

**Comment by rocinant** [comment]
v1.1.4

**Comment by xljiulang** [comment]
1.x版本的fg会修改网络适配器的dns，请使用ctrl+c关闭fg，或者在（不正常）关闭fg之后，到网络适配器设置，设置为自动获取dns。

1.x版已经不维护了，请更新到2.1.1版本

**Comment by rocinant** [comment]
2.1.1版本启动之后好像127.0.0.1进不去，请问是需要手动添加cacert去信任证书吗？还是说跟之前装的1.x有影响

**Comment by xljiulang** [comment]
2.1.1没有主页

**Comment by heartacker** [comment]
2.1.1 我也会出现这样的问题

**Comment by heartacker** [comment]
此站点的连接不安全github.com 发送了无效的响应。
尝试运行 Windows 网络诊断。
ERR_SSL_PROTOCOL_ERROR

**Comment by xljiulang** [comment]
@heartacker 你是关闭了fg了吧
