### ISSUE TITLE
启动异常

### ISSUE THREAD

**Issue by xintingcui** [dotnetcore/FastGithub#94]
系统型号	OMEN by HP Laptop 15-dc1xxx
windows 版本: win 10 家庭版 
版本	10.0.19043 内部版本 19043

2021-11-27T14:03:06.6190101+08:00 [INF]
FastGithub.HttpServer
已监听https://localhost:444，https反向代理服务启动完成

2021-11-27T14:03:06.7170061+08:00 [INF]
FastGithub.HttpServer
已监听http://localhost:80，http反向代理服务启动完成

2021-11-27T14:03:06.7189890+08:00 [INF]
FastGithub.HttpServer
已监听ssh://localhost:22，github的ssh反向代理服务启动完成

2021-11-27T14:03:06.7203872+08:00 [INF]
FastGithub.HttpServer
已监听git://localhost:9418，github的git反向代理服务启动完成

2021-11-27T14:03:06.8068783+08:00 [INF]
FastGithub.AppHostedService
FastGithub启动完成，当前版本为v2.1.1，访问 https://github.com/dotnetcore/fastgithub 关注新版本

2021-11-27T14:03:06.9041328+08:00 [INF]
FastGithub.PacketIntercept.Tcp.HttpsInterceptor
127.0.0.1:443 <=> 127.0.0.1:444

2021-11-27T14:03:06.9090606+08:00 [INF]
FastGithub.PacketIntercept.Tcp.HttpsInterceptor
::1:443 <=> ::1:444

2021-11-27T14:03:07.8340641+08:00 [INF]
FastGithub.AppHostedService
正在主动关闭，因为父进程已退出

**Comment by xljiulang** [comment]
ui自动关闭吗，还是手工退出

**Comment by xintingcui** [comment]
> ui自动关闭吗，还是手工退出

ui没有启动,就结束了

**Comment by xljiulang** [comment]
你直接双击运行fastgithub.exe看看

**Comment by xintingcui** [comment]
> 你直接双击运行fastgithub.exe看看

用 start fastgithub好像是没问题的
