### ISSUE TITLE
无法访问github

### ISSUE THREAD

**Issue by gongkui** [dotnetcore/FastGithub#99]
**Bug描述**
网页提示：
未连接：有潜在的安全问题
Firefox 检测到潜在的安全威胁，并因 github.com 要求安全连接而没有继续。
您可以做什么？
github.com 启用了被称为 HTTP 严格传输安全（HSTS）的安全策略，Firefox 只能与其建立安全连接。您无法为此网站添加例外，以访问此网站。
这个问题大多与网站有关，无法通过您的操作解决。
如果您是在使用公司网络或某些防病毒软件时遇到此问题，可考虑联系客服（技术支持）以寻求帮助。您也可以向网站管理员告知此问题。

-----

通过查看连接不安全选项，可以看到证书颁发者是FastGithub，连接未加密。

**重现步骤**
1.  打开软件
2.  用火狐浏览器访问github.com
 

**软件信息**
 - 操作系统: windows10
 - FastGithub： 默认最新发布

**Comment by xljiulang** [comment]
请看readme
